### ISSUE TITLE
Update client to 6.1.6

### ISSUE THREAD

**Issue by LindyLo** [ketzusaka/mysql-connector-c#3]
Could you kindly share the script used for building ? Or update to 6.1.6

**Comment by ketzusaka** [comment]
Hi,

I built this a longggg time ago, I believe before MySQL switched to cmake. I'm working on updating the library to 6.1.6, and after I do so, I'll include the build instructions in the repo.

**Comment by LindyLo** [comment]
Hi thanks for the reply !
That would be great, thanks.

**Comment by ketzusaka** [comment]
@LindyLo I've updated the library. You can get the 6.1.6 version through cocoapods as version 2.0.0 :)

I'll add a wiki page shortly about the build steps. 

Let me know if you have any problems!

**Comment by LindyLo** [comment]
Thanks a lot, I have successfully built and used it in my swift project.
Wiki page would be just great !

**Comment by ketzusaka** [comment]
Hi @LindyLo, wanted to let you know I threw up the steps I used to get the library building. Please let me know if you have any questions on it if you ever go down that road :)

https://github.com/ketzusaka/mysql-connector-c/wiki
